# Configuration for librarian-puppet. For example:
# 
forge "http://forge.puppetlabs.com"
# 
mod "puppetlabs/vcsrepo"

mod "python",
    :git => "git://github.com/stankevich/puppet-python.git"

# mod "puppetlabs/ntp", "0.0.3"
# 
# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
# 
# mod "stdlib",
#   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
